language: cpp
compiler: gcc
os: linux
dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake
      - valgrind

before_script:
  - gcc -v && g++ -v && cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
#  - make test
