language: cpp
compiler: gcc
os: linux
dist: focal

notifications:
  on_success: never

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake
      - valgrind
      - build-essential
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-dev
      - python-numpy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
#      - libjasper-dev
      - libdc1394-22-dev
      - libproj-dev
#      - proj-bin

before_script:
  # install libjasper-dev that couldn't without new sources
  - sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
  - sudo apt update
  - sudo apt install libjasper1 libjasper-dev

  # verify compilers
  - gcc -v && g++ -v && cmake --version

#  # install and verify proj
#  - wget https://download.osgeo.org/proj/proj-7.2.0.tar.gz
#  - tar xvzf proj-7.2.0.tar.gz
#  - cd proj-7.2.0
#  - ./configure
#  - make
#  - sudo make install
#  - make check

#  # install and verify opencv
#  - cd ..
#  - git clone https://github.com/opencv/opencv.git
#  - git clone https://github.com/opencv/opencv_contrib.git
#  - cd opencv
#  - mkdir build
#  - cd build
#  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
#  - make -j4
#  - sudo make install
#  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
#  - sudo ldconfig
#  - pkg-config --modversion opencv4  trying below without 4 to see if it works

  # return to base of the project
  - cd ../dtm-guerledan
#  - cd ../../dtm-guerledan
  - locate libproj
  - which proj

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
#  - make test
